# Generated by Django 4.2 on 2023-05-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneNumbers', '0003_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Структура', 'verbose_name_plural': 'Структуры'},
        ),
    ]
