# Generated by Django 4.2.2 on 2023-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.FileField(upload_to='services/certificates/', verbose_name='Изображение'),
        ),
    ]
