# Generated by Django 4.2.2 on 2023-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
