# Generated by Django 4.2.2 on 2023-08-14 08:53

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_subsidies_law'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Дата выставки')),
                ('image', models.FileField(upload_to='services/certificates/', verbose_name='Изображение')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
    ]
