# Generated by Django 4.2 on 2023-04-19 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uzCloud', '0002_alter_file_options_alter_folder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
