# Generated by Django 4.2 on 2023-05-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzCloud', '0004_alter_file_author_alter_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
